src/Entity/Seo.php
<?php

namespace App\Entity;

use App\Repository\SeoRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=SeoRepository::class)
 */
class Seo
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $label;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updated_at;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(?string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getLabel(): ?string
    {
        return $this->label;
    }

    public function setLabel(?string $label): self
    {
        $this->label = $label;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(?\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }
}

src/Controller/SitemapController.php
<?php

namespace App\Controller;

use App\Repository\ActivityRepository;
use App\Repository\ContactRepository;
use App\Repository\ExperienceRepository;
use App\Repository\FooterRepository;
use App\Repository\FormationRepository;
use App\Repository\HeaderRepository;
use App\Repository\LeisureRepository;
use App\Repository\SeoRepository;
use App\Repository\SkillRepository;
use App\Repository\UserRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

class SitemapController extends AbstractController
{
    private $userRepository;
    private $contactRepository;
    private $headerRepository;
    private $footerRepository;
    private $activityRepository;
    private $skillRepository;
    private $entityManager;
    private $experienceRepository;
    private $formationRepository;
    private $leisureRepository;
    private $seoRepository;

    public function __construct(UserRepository $userRepository,
                                ContactRepository $contactRepository,
                                HeaderRepository $headerRepository,
                                FooterRepository $footerRepository,
                                ActivityRepository $activityRepository,
                                SkillRepository $skillRepository,
                                EntityManagerInterface $entityManager,
                                ExperienceRepository $experienceRepository,
                                FormationRepository $formationRepository,
                                LeisureRepository $leisureRepository,
                                SeoRepository $seoRepository)
    {
        $this->userRepository = $userRepository;
        $this->contactRepository = $contactRepository;
        $this->headerRepository = $headerRepository;
        $this->footerRepository = $footerRepository;
        $this->activityRepository = $activityRepository;
        $this->skillRepository = $skillRepository;
        $this->entityManager = $entityManager;
        $this->experienceRepository = $experienceRepository;
        $this->formationRepository = $formationRepository;
        $this->leisureRepository = $leisureRepository;
        $this->seoRepository = $seoRepository;
    }

    /**
     * @Route("/sitemap.xml", name="sitemap", defaults={"_format"="xml"})
     */
    public function index()
    {
        $users = $this->userRepository->findAll();
        $contacts = $this->contactRepository->findAll();
        $activities = $this->activityRepository->findAll();
        $headers = $this->headerRepository->findAll();
        $footers = $this->footerRepository->findAll();
        $skills = $this->skillRepository->findAll();
        $experiences = $this->experienceRepository->findAll();
        $formations = $this->formationRepository->findAll();
        $leisure = $this->leisureRepository->findAll();
        $seo = $this->seoRepository->findAll();

        return $this->render('sitemap/index.html.twig', [
            'users' => $users,
            'contacts' => $contacts,
            'activities' => $activities,
            'experiences' => $experiences,
            'formations' => $formations,
            'leisure' => $leisure,
            'headers' => $headers,
            'footers' => $footers,
            'skills' => $skills,
            'seo' => $seo,
        ]);
    }
}

templates/sitemap/index.html.twig
<?xml version="1.0" encoding="UTF-8"?>

<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
        xmlns:xhtml="http://www.w3.org/1999/xhtml"
        xmlns:image="http://www.google.com/schemas/sitemap-image/1.1"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd">

    {% if users is defined and users is not empty %}
        {% for element in users %}
            <url>
                {% if element.name is not empty %}
                    <loc>{{ url('home') ~ '#home' }}</loc>
                {% endif %}
                {% if element.updatedAt is not empty %}
                    <lastmod>{{ element.updatedAt|date("Y/m/d") }}</lastmod>
                {% endif %}
                <changefreq>daily</changefreq>
                <priority>0.8</priority>
            </url>
        {% endfor %}
    {% endif %}

    {% if contacts is defined and contacts is not empty %}
        {% for element in contacts %}
            <url>
                {% if element.name is not empty %}
                    <loc>{{ url('home') ~ '#contact-me' }}</loc>
                {% endif %}
                {% if element.updatedAt is not empty %}
                    <lastmod>{{ element.updatedAt|date("Y/m/d") }}</lastmod>
                {% endif %}
                <changefreq>daily</changefreq>
                <priority>0.8</priority>
            </url>
        {% endfor %}
    {% endif %}

    {% if activities is defined and activities is not empty %}
        {% for element in activities %}
            <url>
                {% if element.name is not empty %}
                    <loc>{{ url('home') ~ '#activity' }}</loc>
                {% endif %}
                {% if element.updatedAt is not empty %}
                    <lastmod>{{ element.updatedAt|date("Y/m/d") }}</lastmod>
                {% endif %}
                <changefreq>daily</changefreq>
                <priority>0.8</priority>
            </url>
        {% endfor %}
    {% endif %}

    {% if experiences is defined and experiences is not empty %}
        {% for element in experiences %}
            <url>
                {% if element.name is not empty %}
                    <loc>{{ url('home') ~ '#portfolio' }}</loc>
                {% endif %}
                {% if element.updatedAt is not empty %}
                    <lastmod>{{ element.updatedAt|date("Y/m/d") }}</lastmod>
                {% endif %}
                <changefreq>daily</changefreq>
                <priority>0.8</priority>
            </url>
        {% endfor %}
    {% endif %}

    {% if formations is defined and formations is not empty %}
        {% for element in formations %}
            <url>
                {% if element.name is not empty %}
                    <loc>{{ url('home') }}</loc>
                {% endif %}
                {% if element.updatedAt is not empty %}
                    <lastmod>{{ element.updatedAt|date("Y/m/d") }}</lastmod>
                {% endif %}
                <changefreq>daily</changefreq>
                <priority>0.8</priority>
            </url>
        {% endfor %}
    {% endif %}
</urlset>